development:
  adapter: postgresql
  encoding: unicode
  database: chatbot_dev
  pool: 5
  username: mrreaksmey
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chatbot_test
  pool: 5
  username: mrreaksmey
  password: