# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8509b72464ea4d73c1a0b446afa23487f6a870c456885bd9095c0014a52a2d4bb96fb48b52c2ca5edb2a4f7c454fc21aaa9babefc0ef14e35e94201b581d4b75

test:
  secret_key_base: 25ce20baa5efb2b2f48a741c3e8b92d95a1a95ed81193cca6ab78cb7ced144d2c11204a15673474629329c5d394efd1d4b798a3cf06f5075808153055030a139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
